In [41]:
import numpy as np
n=int(input("행의값을 입력하여라"))
s = int(input("Seed값을 입력하여라"))
a = np.empty((n,n))
seed = s
for  j in range(0,n) :
    for i in range(0,j+1) :
        a[i,j] = seed  
        seed = seed+1
        if seed == 10:
            seed = 1
    
print(a)

행의값을 입력하여라3
Seed값을 입력하여라9
[[9. 1. 3.]
 [0. 2. 4.]
 [0. 0. 5.]]
